# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Sobre Mim',   url: 'about.html'}
- {name: 'Posts', url: 'posts.html'}
- {name: 'Contato', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/renesoaresse'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/rene-soares'}
- {icon: 'envelope',   link: 'mailto:reenerochase@gmail.com'}
- {icon: 'rss-square', link: '/rss-feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Próximo'
  previous_page: 'Anterior'

sharing_button_prompt: 'Sinta-se à vontade para compartilhar!'

related_posts: 'Você também pode gostar:'

post_date_prefix: 'Escrito em'
